import { Link } from "@tanstack/react-router";
import { ArrowRight, Award } from "lucide-react";
import { Button } from "@/components/ui/button";
import { testimonials } from "@/lib/studio-data";

export function PageHero({eyebrow,title,copy,image}:{eyebrow:string;title:string;copy:string;image:string}){return <section className="relative min-h-[58vh] overflow-hidden"><img src={image} alt="" className="absolute inset-0 h-full w-full object-cover" width={1600} height={1000}/><div className="absolute inset-0 bg-hero-overlay"/><div className="relative mx-auto flex min-h-[58vh] max-w-[1440px] items-end px-5 pb-14 text-background lg:px-10 lg:pb-20"><div className="max-w-3xl animate-fade-in"><p className="eyebrow text-blush">{eyebrow}</p><h1 className="mt-4 text-5xl md:text-7xl">{title}</h1><p className="mt-5 max-w-xl text-lg text-background/80">{copy}</p></div></div></section>}
export function SectionIntro({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="max-w-3xl"><p className="eyebrow">{eyebrow}</p><h2 className="mt-4 text-4xl md:text-6xl">{title}</h2>{copy&&<p className="mt-5 max-w-2xl text-lg text-muted-foreground">{copy}</p>}</div>}
export function AwardMark(){return <div className="flex items-center gap-5 border-y border-gold py-5"><Award className="size-9 shrink-0 text-gold"/><div><p className="eyebrow text-primary">Industry recognition</p><p className="mt-1 font-display text-2xl">Proud industry awards finalist</p></div></div>}
export function Testimonials({limit=3}:{limit?:number}){return <section className="bg-blush py-20"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionIntro eyebrow="Kind words" title="From the studio and the classroom"/><div className="mt-12 grid gap-px bg-gold/40 md:grid-cols-2 lg:grid-cols-3">{testimonials.slice(0,limit).map((t,i)=><blockquote key={i} className="bg-blush p-7 lg:p-9"><p className="font-display text-2xl leading-snug">“{t.quote}”</p><footer className="mt-6 text-sm text-muted-foreground">{t.by}</footer></blockquote>)}</div></div></section>}
export function TextLink({to,children}:{to:string;children:React.ReactNode}){return <Button asChild variant="link" className="px-0"><Link to={to}>{children}<ArrowRight/></Link></Button>}
export function DemoNote(){return <p className="border-l-2 border-gold pl-4 text-sm text-muted-foreground">Visual preview only. Nothing entered, selected or confirmed here is sent or booked.</p>}
